# frozen_string_literal: true

# TODO: Replace with actual config model once implemented. This is a temporary implementation
# generated by claude to facilitate development of the exemption screener feature.

# ExemptionScreenerConfig
#
# Loads and provides access to the exemption screener configuration.
# This is a temporary implementation using a YAML file.
# Will be replaced with a database-backed or more sophisticated solution on a separate branch.
#
# Usage:
#   config = ExemptionScreenerConfig.new
#   config.exemption_types # => ["medical_condition", "substance_use_treatment", ...]
#   config.questions_for("medical_condition") # => [{question: "...", description: "...", yes_answer: "..."}, ...]
#   config.total_questions_count # => 8
#
class ExemptionScreenerConfig
  CONFIG_PATH = Rails.root.join("config", "exemption_screener_config.yml")

  def initialize
    @config = load_config
  end

  # Returns array of exemption type keys in order
  # Only includes enabled exemption types
  def exemption_types
    @exemption_types ||= @config
      .select { |_key, value| value["enable"] }
      .sort_by { |_key, value| value["order"] }
      .map(&:first)
      .map(&:to_s)
  end

  # Returns array of question hashes for a given exemption type
  # Each hash contains: question, description, yes_answer
  def questions_for(exemption_type)
    exemption_config = config_for(exemption_type)
    return [] unless exemption_config

    exemption_config["questions"] || []
  end

  # Returns the full configuration hash for a given exemption type
  # Returns nil if exemption type doesn't exist or is not enabled
  def config_for(exemption_type)
    exemption_config = @config[exemption_type.to_s] || @config[exemption_type.to_sym]
    return nil unless exemption_config && exemption_config["enable"]

    exemption_config
  end

  # Returns the name for a given exemption type
  def name_for(exemption_type)
    config = config_for(exemption_type)
    config&.fetch("name", exemption_type.to_s.titleize)
  end

  # Returns the description for a given exemption type
  def description_for(exemption_type)
    config = config_for(exemption_type)
    config&.fetch("description", "")
  end

  # Returns the documentation intro text for a given exemption type
  def documentation_intro_for(exemption_type)
    config = config_for(exemption_type)
    config&.fetch("documentation_intro", "")
  end

  # Returns the array of required documents for a given exemption type
  def required_documents_for(exemption_type)
    config = config_for(exemption_type)
    config&.fetch("required_documents", [])
  end

  # Returns total number of questions across all enabled exemption types
  def total_questions_count
    exemption_types.sum { |type| questions_for(type).count }
  end

  # Returns the exemption type and question index for a given absolute question number (1-indexed)
  # Returns [exemption_type, question_index] or [nil, nil] if out of range
  def exemption_and_question_for_absolute_position(position)
    current_position = 0

    exemption_types.each do |exemption_type|
      question_count = questions_for(exemption_type).count
      if position <= current_position + question_count
        question_index = position - current_position - 1
        return [ exemption_type, question_index ]
      end
      current_position += question_count
    end

    [ nil, nil ]
  end

  # Returns the absolute question position (1-indexed) for a given exemption type and question index
  def absolute_position_for(exemption_type, question_index)
    position = 1

    exemption_types.each do |type|
      if type == exemption_type
        return position + question_index
      end
      position += questions_for(type).count
    end

    nil
  end

  # Returns the next exemption type and question index
  # Returns [exemption_type, question_index] or [nil, nil] if at end
  def next_question(current_exemption_type, current_question_index)
    questions = questions_for(current_exemption_type)

    # Check if there's another question in the current exemption type
    if current_question_index + 1 < questions.count
      return [ current_exemption_type, current_question_index + 1 ]
    end

    # Move to next exemption type
    current_type_index = exemption_types.index(current_exemption_type)
    return [ nil, nil ] unless current_type_index

    next_type_index = current_type_index + 1
    return [ nil, nil ] if next_type_index >= exemption_types.count

    next_exemption_type = exemption_types[next_type_index]
    [ next_exemption_type, 0 ]
  end

  # Returns the previous exemption type and question index
  # Returns [exemption_type, question_index] or [nil, nil] if at beginning
  def previous_question(current_exemption_type, current_question_index)
    # Check if there's a previous question in the current exemption type
    if current_question_index > 0
      return [ current_exemption_type, current_question_index - 1 ]
    end

    # Move to previous exemption type's last question
    current_type_index = exemption_types.index(current_exemption_type)
    return [ nil, nil ] unless current_type_index
    return [ nil, nil ] if current_type_index.zero?

    previous_exemption_type = exemption_types[current_type_index - 1]
    last_question_index = questions_for(previous_exemption_type).count - 1
    [ previous_exemption_type, last_question_index ]
  end

  # Validates if exemption type and question index are valid
  def valid_question?(exemption_type, question_index)
    return false unless exemption_types.include?(exemption_type)
    return false unless question_index.is_a?(Integer) && question_index >= 0

    questions = questions_for(exemption_type)
    question_index < questions.count
  end

  private

  def load_config
    YAML.load_file(CONFIG_PATH)
  rescue Errno::ENOENT
    Rails.logger.error("Exemption screener config file not found at #{CONFIG_PATH}")
    {}
  rescue Psych::SyntaxError => e
    Rails.logger.error("Error parsing exemption screener config: #{e.message}")
    {}
  end
end
