plugins:
  - rubocop-rspec
inherit_gem:
  pundit: config/rubocop-rspec.yml
  rubocop-rails-omakase: rubocop.yml

RSpec/IncludeExamples:
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
