services:
  reporting-app:
    build:
      context: ../reporting-app
      target: dev
    environment:
      RAILS_ENV: development
      DB_HOST: reporting-app-database
      DB_PORT: "5432"
      RAILS_BINDING: 0.0.0.0
      BUNDLE_PATH: /usr/local/bundle
      GEM_HOME: /usr/local/bundle
    volumes:
      # Mount entire project root to /workspace for full project access
      - ..:/workspace:cached
      # Keep Rails app mounted at /rails for compatibility (from base compose)
      # Base: - .:/rails  (will be: ../reporting-app:/rails)
      # Named volumes for performance (override base compose paths)
      - reporting-app_nodemodules:/workspace/reporting-app/node_modules
      - reporting-app_nodemodules:/rails/node_modules
      - reporting-app_tmp:/workspace/reporting-app/tmp
      - reporting-app_tmp:/rails/tmp
      - reporting-app_storage:/workspace/reporting-app/storage
      - reporting-app_storage:/rails/storage
      - reporting-app_log:/workspace/reporting-app/log
      - reporting-app_log:/rails/log
    command: sleep infinity
    working_dir: /workspace

  reporting-app-database:
    environment:
      POSTGRES_PASSWORD: secret123
      POSTGRES_USER: app
      POSTGRES_DB: app

volumes:
  reporting-app_nodemodules:
  reporting-app_tmp:
  reporting-app_storage:
  reporting-app_log:



