# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/activities", type: :request do
  include Warden::Test::Helpers

  let(:user) { User.create!(email: "test@example.com", uid: SecureRandom.uuid, provider: "login.gov") }

  let(:other_user) { User.create!(email: "test-other@example.com", uid: SecureRandom.uuid, provider: "login.gov") }

  let!(:activity_report_application_form) { create(:activity_report_application_form, :with_activities, user_id: user.id) }
  let!(:existing_activity) { activity_report_application_form.activities.first }

  # This should return the minimal set of attributes required to create a valid
  # Activity. As you add validations to Activity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "Acme Corp",
      hours: 80.0,
      month: (Date.today - 1.month).beginning_of_month
    }
  }

  let(:valid_db_attributes) do
    valid_request_attributes.merge!(
      {
        user_id: user.id
      }
    )
  end

  let(:invalid_attributes) {
    {
      name: "",
      hours: "Not a number"
    }
  }

  before do
    login_as user
  end

  after do
    Warden.test_reset!
  end

  describe "GET /show" do
    it "renders a successful response" do
      get activity_report_application_form_activity_url(activity_report_application_form, existing_activity)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_activity_report_application_form_activity_url(activity_report_application_form)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      get edit_activity_report_application_form_activity_url(activity_report_application_form, existing_activity)
      expect(response).to be_successful
    end
  end

  describe "GET /documents" do
    it "renders a successful response" do
      get documents_activity_report_application_form_activity_url(activity_report_application_form, existing_activity)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Activity" do
        expect {
          post activity_report_application_form_activities_url(activity_report_application_form), params: { activity: valid_attributes }
        }.to change(Activity, :count).by(1)
      end

      it "redirects to the activity report" do
        post activity_report_application_form_activities_url(activity_report_application_form), params: { activity: valid_attributes }

        expect(response).to have_http_status(:redirect)
        expect(response.location).to match(%r{/activity_report_application_forms/#{activity_report_application_form.id}/activities/[^/]+/documents})
      end
    end

    context "with invalid parameters" do
      it "does not create a new Activity" do
        expect {
          post activity_report_application_form_activities_url(activity_report_application_form), params: { activity: invalid_attributes }
        }.not_to change(Activity, :count)
      end

      it "renders a response with 422 status (unprocessable entity)" do
        post activity_report_application_form_activities_url(activity_report_application_form), params: { activity: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

      it "renders error messages" do
        post activity_report_application_form_activities_url(activity_report_application_form), params: { activity: invalid_attributes }
        expect(response.body).to include("Hours is not a number")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "New Employer Corp",
          hours: 100.0
        }
      }

      before do
        patch activity_report_application_form_activity_url(activity_report_application_form, existing_activity), params: { activity: new_attributes }
      end

      it "updates the requested activity" do
        activity_report_application_form.reload
        updated_activity = activity_report_application_form.activities_by_id[existing_activity.id]
        expect(updated_activity.name).to eq("New Employer Corp")
        expect(updated_activity.hours).to eq(100.0)
        # expect(updated_activity.supporting_documents.count).to eq(1)
        # expect(updated_activity.supporting_documents.first.filename.to_s).to eq("test_document_2.txt")
      end

      it "redirects to the activity report" do
        expect(response).to redirect_to(documents_activity_report_application_form_activity_url(activity_report_application_form, existing_activity))
      end
    end

    context "with invalid parameters" do
      before do
        patch activity_report_application_form_activity_url(activity_report_application_form, existing_activity), params: { activity: invalid_attributes }
      end

      it "renders a response with 422 status (unprocessable entity)" do
        expect(response).to have_http_status(:unprocessable_entity)
      end

      it "renders error messages" do
        expect(response.body).to include("Hours is not a number")
      end

      it "does not update the activity" do
        activity_report_application_form.reload
        updated_activity = activity_report_application_form.activities_by_id[existing_activity.id]
        expect(updated_activity.name).not_to eq("")
        expect(updated_activity.hours).not_to eq("Not a number")
      end
    end
  end

  describe "POST /upload_document" do
    let(:supporting_documents) { [
      fixture_file_upload('spec/fixtures/files/test_document_1.pdf', 'application/pdf'),
      fixture_file_upload('spec/fixtures/files/test_document_2.txt', 'text/plain')
    ] }

    before do
      post upload_documents_activity_report_application_form_activity_url(activity_report_application_form, existing_activity),
        params: { activity: { supporting_documents: supporting_documents } }
    end

    it "redirects back to the documents page" do
      expect(response).to redirect_to(documents_activity_report_application_form_activity_url(activity_report_application_form, existing_activity))
    end

    it "uploads the documents" do
      existing_activity.reload
      expect(existing_activity.supporting_documents.count).to eq(2)
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested activity" do
      expect {
        delete activity_report_application_form_activity_url(activity_report_application_form, existing_activity)
      }.to change(Activity, :count).by(-1)
    end

    it "redirects to the activities list" do
      delete activity_report_application_form_activity_url(activity_report_application_form, existing_activity)
      expect(response).to redirect_to(activity_report_application_form_url(activity_report_application_form))
    end
  end
end
