require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/exemption_application_forms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ExemptionApplicationForm. As you add validations to ExemptionApplicationForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExemptionApplicationForm.create! valid_attributes
      get exemption_application_forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      exemption_application_form = ExemptionApplicationForm.create! valid_attributes
      get exemption_application_form_url(exemption_application_form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_exemption_application_form_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      exemption_application_form = ExemptionApplicationForm.create! valid_attributes
      get edit_exemption_application_form_url(exemption_application_form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExemptionApplicationForm" do
        expect {
          post exemption_application_forms_url, params: { exemption_application_form: valid_attributes }
        }.to change(ExemptionApplicationForm, :count).by(1)
      end

      it "redirects to the created exemption_application_form" do
        post exemption_application_forms_url, params: { exemption_application_form: valid_attributes }
        expect(response).to redirect_to(exemption_application_form_url(ExemptionApplicationForm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExemptionApplicationForm" do
        expect {
          post exemption_application_forms_url, params: { exemption_application_form: invalid_attributes }
        }.to change(ExemptionApplicationForm, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post exemption_application_forms_url, params: { exemption_application_form: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested exemption_application_form" do
        exemption_application_form = ExemptionApplicationForm.create! valid_attributes
        patch exemption_application_form_url(exemption_application_form), params: { exemption_application_form: new_attributes }
        exemption_application_form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the exemption_application_form" do
        exemption_application_form = ExemptionApplicationForm.create! valid_attributes
        patch exemption_application_form_url(exemption_application_form), params: { exemption_application_form: new_attributes }
        exemption_application_form.reload
        expect(response).to redirect_to(exemption_application_form_url(exemption_application_form))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        exemption_application_form = ExemptionApplicationForm.create! valid_attributes
        patch exemption_application_form_url(exemption_application_form), params: { exemption_application_form: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested exemption_application_form" do
      exemption_application_form = ExemptionApplicationForm.create! valid_attributes
      expect {
        delete exemption_application_form_url(exemption_application_form)
      }.to change(ExemptionApplicationForm, :count).by(-1)
    end

    it "redirects to the exemption_application_forms list" do
      exemption_application_form = ExemptionApplicationForm.create! valid_attributes
      delete exemption_application_form_url(exemption_application_form)
      expect(response).to redirect_to(exemption_application_forms_url)
    end
  end
end
