plugins:
  - rubocop-rspec
inherit_gem:
  pundit: config/rubocop-rspec.yml
  rubocop-rails-omakase: rubocop.yml

RSpec/IncludeExamples:
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/NoExpectationExample:
  AllowedPatterns:
    - assert_
    - is_expected_in_block

Style/FrozenStringLiteralComment:
  Enabled: true
