{
  "components": {
    "schemas": {
      "CertificationCreateRequestBody": {
        "type": "object",
        "properties": {
          "member_id": {
            "type": "string",
            "description": "An identifier for the person receiving benefits"
          },
          "case_number": {
            "type": [
              "string",
              "null"
            ],
            "description": "An identifier for the case associated with the certification"
          },
          "certification_requirements": {
            "oneOf": [
              {
                "$ref": "#/components/schemas/CertificationRequirements"
              },
              {
                "$ref": "#/components/schemas/CertificationRequirementParameters"
              },
              {
                "$ref": "#/components/schemas/CertificationRequirementTypeParameters"
              }
            ]
          },
          "member_data": {
            "type": [
              "object",
              "null"
            ],
            "description": "Description of beneficiary",
            "properties": {}
          }
        },
        "required": [
          "member_id",
          "certification_requirements"
        ],
        "examples": {
          "fully_specified_certification_requirements": {
            "value": {
              "member_id": "123",
              "case_number": "C-111",
              "certification_requirements": {
                "certification_date": "2025-09-26",
                "lookback_period": 3,
                "number_of_months_to_certify": 1,
                "due_period_days": 30
              },
              "member_data": {
                "contact": {
                  "email": "john@doe.com",
                  "phone": "+123456789"
                }
              }
            }
          },
          "certification_type": {
            "value": {
              "member_id": "123",
              "case_number": "C-111",
              "certification_requirements": {
                "certification_date": "2025-09-26",
                "certification_type": "new_application"
              },
              "member_data": {
                "contact": {
                  "email": "john@doe.com",
                  "phone": "+123456789"
                }
              }
            }
          }
        }
      },
      "CertificationRequirements": {
        "type": "object",
        "description": "Description of certification needs",
        "properties": {
          "certification_date": {
            "type": "string",
            "format": "date",
            "description": "The date of the certification"
          },
          "certification_type": {
            "type": [
              "string",
              "null"
            ],
            "description": "The type of certification"
          },
          "months_that_can_be_certified": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "date"
            },
            "description": "The list of months the Member can choose from"
          },
          "number_of_months_to_certify": {
            "type": "integer",
            "description": "The number of months the Member needs to certify"
          },
          "due_date": {
            "type": "string",
            "format": "date",
            "description": "Date by which the Member must have submitted their evidence"
          },
          "params": {
            "type": [
              "object",
              "null"
            ],
            "description": "Input parameters, if any.",
            "properties": {}
          }
        },
        "required": [
          "certification_date",
          "months_that_can_be_certified",
          "number_of_months_to_certify",
          "due_date"
        ]
      },
      "CertificationRequirementParameters": {
        "type": "object",
        "properties": {
          "certification_date": {
            "type": "string",
            "format": "date",
            "description": "The date of the certification"
          },
          "lookback_period": {
            "type": "integer",
            "description": "The number of months before `certification_date` the Member can choose from"
          },
          "number_of_months_to_certify": {
            "type": "integer",
            "description": "The number of months the Member needs to certify"
          },
          "due_period_days": {
            "type": "integer"
          }
        },
        "required": [
          "certification_date",
          "lookback_period",
          "number_of_months_to_certify",
          "due_period_days"
        ]
      },
      "CertificationRequirementTypeParameters": {
        "type": "object",
        "properties": {
          "certification_date": {
            "type": "string",
            "format": "date",
            "description": "The date of the certification"
          },
          "certification_type": {
            "type": "string",
            "description": "The type of certification"
          }
        },
        "required": [
          "certification_date",
          "certification_type"
        ]
      },
      "CertificationResponseBody": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "description": "Identifier for the certification record"
          },
          "member_id": {
            "type": "string",
            "description": "An identifier for the person receiving benefits"
          },
          "case_number": {
            "type": [
              "string",
              "null"
            ],
            "description": "An identifier for the case associated with the certification"
          },
          "certification_requirements": {
            "$ref": "#/components/schemas/CertificationRequirements"
          },
          "member_data": {
            "type": [
              "object",
              "null"
            ],
            "description": "Description of beneficiary",
            "properties": {}
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "id",
          "member_id",
          "created_at",
          "updated_at"
        ],
        "example": {
          "id": "63680317-0e33-40a7-8e1a-249a2f5855d9",
          "member_id": "123",
          "case_number": "C-111",
          "certification_requirements": {
            "certification_date": "2025-09-26",
            "number_of_months_to_certify": 1,
            "due_date": "2025-10-36",
            "params": {
              "lookback_period": 3,
              "number_of_months_to_certify": 1,
              "due_period_days": 30
            }
          },
          "member_data": {
            "contact": {
              "email": "john@doe.com",
              "phone": "+123456789"
            }
          },
          "created_at": "1970-01-01T00:00:00.000Z",
          "updated_at": "1970-01-01T00:00:00.000Z"
        }
      },
      "ErrorResponseBody": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "status"
        ],
        "example": {
          "status": 400
        }
      },
      "bf2b49f733c3ee403393efcf6916e8be": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "status"
        ]
      }
    },
    "responses": {
      "695fcb0c4182127d82f4e9feca6c3107": {
        "description": "Created Certification.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CertificationResponseBody"
            }
          }
        }
      },
      "5230f591420b11a3e6a1b73574262bb5": {
        "description": "User error.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponseBody"
            }
          }
        }
      },
      "66e42391a76944e2fc8bad47d01d4c48": {
        "description": "The server could not process the request due to semantic errors. Please check your input and try again.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/bf2b49f733c3ee403393efcf6916e8be"
            }
          }
        }
      },
      "ba1b34eb2492ad585b4fe0377d889e5b": {
        "description": "A Certification",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CertificationResponseBody"
            }
          }
        }
      },
      "b0b402a94452e7d59e0e4417da868c06": {
        "description": "The requested resource could not be found.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/bf2b49f733c3ee403393efcf6916e8be"
            }
          }
        }
      }
    },
    "parameters": {
      "49e46dd8af57e26752938ebb0d0ec979": {
        "name": "id",
        "in": "path",
        "description": "Id of existing certification.",
        "required": true,
        "schema": {
          "type": "string"
        },
        "style": "simple"
      }
    },
    "requestBodies": {
      "90c3f9f1ee6ac4ddeb67e63d771ff499": {
        "description": "The Certification data.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CertificationCreateRequestBody"
            },
            "examples": {
              "fully_specified_certification_requirements": {
                "$ref": "#/components/schemas/CertificationCreateRequestBody/examples/fully_specified_certification_requirements"
              },
              "certification_type": {
                "$ref": "#/components/schemas/CertificationCreateRequestBody/examples/certification_type"
              }
            }
          }
        },
        "required": false
      }
    },
    "securitySchemes": {},
    "headers": {},
    "examples": {},
    "links": {},
    "callbacks": {}
  },
  "openapi": "3.1.0",
  "info": {
    "title": "Community Engagement Medicaid",
    "summary": "OasRails: Automatic Interactive API Documentation for Rails",
    "description": "# Welcome to the Community Engagement Medicaid API\n\nThis is the OpenAPI spec for interacting with the Community Engagement Medicaid API.\n\n## Getting Started\n\nYou will need credentials generated for you by the operations team.\n",
    "termsOfService": "",
    "contact": {
      "name": "Nava PBC",
      "url": "https://github.com/navapbc/community-engagement-medicaid",
      "email": "medicaid@navapbc.com"
    },
    "license": {
      "name": "TODO",
      "url": "TODO"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local"
    },
    {
      "url": "http://medicaid.navateam.com",
      "description": "Dev"
    }
  ],
  "paths": {
    "/api/certifications": {
      "post": {
        "tags": [
          "Certifications"
        ],
        "summary": "Create a Certification record",
        "description": "#",
        "operationId": "POST__api_certifications",
        "requestBody": {
          "$ref": "#/components/requestBodies/90c3f9f1ee6ac4ddeb67e63d771ff499"
        },
        "responses": {
          "201": {
            "$ref": "#/components/responses/695fcb0c4182127d82f4e9feca6c3107"
          },
          "400": {
            "$ref": "#/components/responses/5230f591420b11a3e6a1b73574262bb5"
          },
          "422": {
            "$ref": "#/components/responses/66e42391a76944e2fc8bad47d01d4c48"
          }
        }
      }
    },
    "/api/certifications/{id}": {
      "get": {
        "tags": [
          "Certifications"
        ],
        "summary": "Retrieve a Certification record",
        "description": "#",
        "operationId": "GET__api_certifications_{id}",
        "parameters": [
          {
            "$ref": "#/components/parameters/49e46dd8af57e26752938ebb0d0ec979"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/ba1b34eb2492ad585b4fe0377d889e5b"
          },
          "404": {
            "$ref": "#/components/responses/b0b402a94452e7d59e0e4417da868c06"
          }
        }
      }
    }
  }
}