name: CI Infra Checks

on:
  push:
    branches:
      - main
    paths:
      - bin/**
      - infra/**
      - .github/workflows/**
  pull_request:
    paths:
      - bin/**
      - infra/**
      - .github/workflows/**

jobs:
  check-compliance-with-tfsec:
    name: Check compliance with tfsec
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Run tfsec check
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          exit-code: '1'
          skip-files: infra/modules/identity-provider/resources/main.tf
