name: CI Vulnerability Scans - reporting-app

on:
  push:
    branches:
      - main
    paths:
      - reporting-app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-reporting-app-vulnerability-scans.yml
  pull_request:
    paths:
      - reporting-app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-reporting-app-vulnerability-scans.yml

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: "reporting-app"
