# Update OpenAPI docs so that they remain up to date with the application
name: Update OpenAPI Docs

on:
  pull_request:
    paths:
      - reporting-app/**
      - Makefile
      - .github/workflows/ci-reporting-app-openapi.yml

defaults:
  run:
    working-directory: ./reporting-app

# Only trigger run one update of the OpenAPI spec at a time on the branch.
# If new commits are pushed to the branch, cancel in progress runs and start
# a new one.
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  update-openapi-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the feature branch associated with the pull request
          ref: ${{ github.head_ref }}

      - name: Update OpenAPI spec
        run: make openapi-spec

      - name: Push changes
        run: |
          git config user.name nava-platform-bot
          git config user.email platform-admins@navapbc.com
          git add --all
          # If there are meaningful changes, commit them. We ignore lines that
          # look to reference autogenerated model IDs, as OasRails does not
          # produce stable IDs for those
          git diff-index \
            --quiet HEAD \
            --ignore-matching-lines='ref": .*\/[0-9a-z]{32}"$' \
            --ignore-matching-lines='"[0-9a-z]{32}": \{' \
            || git commit -m "Update OpenAPI spec"
          git push
