name: CI reporting-app

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .github/workflows/ci-reporting-app.yml
  pull_request:
    paths:
      - app/**
      - .github/workflows/ci-reporting-app.yml

defaults:
  run:
    working-directory: ./reporting-app

jobs:
  # As an enhancement, it is possible to share the built docker image and share
  # it across jobs as described in:
  # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/compose/issues/1973
      - name: Create required env files
        working-directory: ./
        run: |
          touch ./app/.env

      - run: make lint-ci

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make init-container
      - run: make precompile-assets

      - name: Start tests
        run: make test
